import sqlite3

connection = sqlite3.connect("gratitude_list.db")
cursor = connection.cursor()

gratitudes = [
    "Family who loves you",
    "Friends you relate to",
    "Significant other who reminds you you are not alone",
    "Eyes that allow you to see the beauty of the world",
    "Ears that allow you to listen to music",
    "Nose that allows you to smell",
    "Arms that allow you to hold a newborn baby",
    "Legs that give you the freedom to move",
    "Mouth that lets you taste delicious food",
    "Ability to talk",
    "Friendly neighbors who smile at you",
    "Morning coffee for jolting you awake",
    "Libraries with endless books allowing you to learn",
    "Music that helps you feel",
    "Tehe beauty of Mother nature",
    "Today because you have been given it",
    "Art that mesmerizes you",
    "The comfort of your own home",
    "Access to food",
    "Having a steady pay check",
    "Weekends that give you more time to spend on life",
    "The internet which helps you find what you are looking for",
    "Clean water to drink from",
    "A hot shower",
    "A healthy body",
    "Your unique personality",
    "Your strength to keep going when things get tough",
    "Your favorite happy memories",
    "Belly laughs",
    "Watching the sunset in the evening",
    "Pets that bring you all the joy",
    "Kind hearted strangers that show you love",
    "Doctors who have healed you",
    "Forgiveness from someone you hurt",
    "The first snowfall in the winter",
    "Christmas Eve dinner",
    "Getting another chance to a fresh start on New Years Day",
    "A sunny day in the outdoors",
    "Dancing in the rain",
    "Romantic proposals",
    "Your happiest moment",
    "Watching waves crash into boulders",
    "Getting mail from a friend",
    "Sleeping in your bed",
    "Staying up all night talking to an amazing person",
    "Wishing on a shooting star",
    "Going to an event you have been waiting for for months",
    "Being on vacation",
    "Finishing a big project",
    "Dancing at a wedding",
    "A good sleep at night",
    "A quiet moment of solitude",
    "The ability to meditate",
    "Having a functioning brain",
    "Being self-aware",
    "Finding something you have lost",
    "Learning to let go",
    "All that knowledge stored up in your brain",
    "Your growth throughout your life",
    "Your willingness to help others",
    "Your ability to make good decisions",
    "The fact that you are still hopeful that things will get better",
    "The recognition you received on a project",
    "Silly coworkers who make the day more fun",
    "Clean laundry",
    "The smell of lavender",
    "Your freedom",
    "Having things money can not buy",
    "Eating your favorite food",
    "Connecting with others on social media",
    "Someone holding the door for you",
    "A friend calling to check-in",
    "Compliments from strangers",
    "Surprise gifts",
    "The ability to improve your life",
    "Your quirky talents",
    "Feeling safe",
    "Activities that turn your brain off",
    "Being able to read this",
    "Long weekends",
    "Comfortable shoes",
    "Starlit skies",
    "Rainbows after the storm",
    "Thank you notes",
    "Comfy robes",
    "New adventures",
    "No physical pain",
    "Kind strangers",
    "A walk in the forest",
    "Learning something new",
    "Autumn leaves",
    "First warm day after a cold winter",
    "Watching the first snowfall",
    "Positive comments on posts",
    "Having that one friend who likes all your social media posts",
    "Finding money in your pocket",
    "Finding a toilet when you really need to go",
    "Getting the last parking spot",
    "A driver letting you pass in front of them",
    "Having healthy family and friends",
    "Working from home",
    "Singing karaoke with friends",
    "Pursuing your favorite hobby",
    "The feeling you get when you help someone",
    "Getting goosebumps",
    "A first kiss",
    "Finding the answer to your problem",
    "Having electricity",
    "Lunch breaks",
    "Amusement parks",
    "People who support you",
    "Seeing a puppy on the street",
    "The feeling of discovering of an amazing new show",
    "Getting help when you need it",
    "The freedom to speak your mind",
    "Watching holiday movies on the couch",
    "Learning a new perspective",
    "The smell of a new book",
    "Endorphins flowing through you after a workout",
    "Quality time with grandparents",
    "The smell of fresh cut grass",
    "Clean air",
    "Being on a winning team",
    "Getting positive feedback",
    "Doing meaningful work",
    "Street lights",
    "The ability to write things and express yourself"
]

cursor.execute("CREATE TABLE gratitudes (id INTEGER PRIMARY KEY AUTOINCREMENT, phrase TEXT)")
for i in range(len(gratitudes)):
    cursor.execute("INSERT INTO gratitudes (phrase) VALUES (?)", [gratitudes[i]])
    print("added", gratitudes[i])

connection.commit()
connection.close()
